### ISSUE TITLE
Limit login locks even if a different user ID is used

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/hm-limit-login-attempts#13]
Is it normal that after one user is locked out, attempting to login with a _different_ user ID is also blocked?

**Steps to reproduce**
1. Login as an admin/super admin and create a dummy user account
2. Log out and attempt to log in incorrectly as the dummy 4 times.
3. Attempt to log in as the admin/super admin
4. The lock is still in place.

**Comment by roborourke** [comment]
If the lockout is configured to use the current IP address then yes this is expected. It's more about the source of the login than specifically which user is logging in.
